### ISSUE TITLE
Plugin Version versus PrimeFaces version

### ISSUE THREAD

**Issue by escay** [quarkiverse/quarkus-primefaces#121]
Hi,

the versioning description is:

> The versioning of this extension will follow the pattern <code>[quarkus.version].[primefaces.version].[patch]</code>. For example:
> 
> 3.13.0 | Quarkus 3 (EEE10), PrimeFaces 13, Revision 0

what is the best way to define an exact PrimeFaces version like 13.0.1?
I see in the https://repo1.maven.org/maven2/io/quarkiverse/primefaces/quarkus-primefaces/3.13.4/quarkus-primefaces-3.13.4.pom
the version being the latest from maven:

<dependency>
<groupId>org.primefaces</groupId>
<artifactId>primefaces</artifactId>
<classifier>jakarta</classifier>
</dependency>

which could become 14.0.0 in the future automagically.

Could you document your preferred way to influence this? 
I understand you rather not hard code the primefaces version in the quarkus-primefaces-3.13.4.pom

Should I just force the version number to 13.0.1 by using maven dependencyManagement?

**Comment by melloware** [comment]
You don't need to. 3.13.4 is using 13.0.1 already.  As soon as 13.0.2 comes out I will release 3.13.5 

The 3rd digit here is our minor release number.

**Comment by escay** [comment]
I understand the minor number. 

I only saw the 
`
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
`
in <artifactId>quarkus-primefaces</artifactId>, without an explicit version. 

But looking further I see:

parent:
https://repo1.maven.org/maven2/io/quarkiverse/primefaces/quarkus-primefaces-parent/3.13.4/quarkus-primefaces-parent-3.13.4.pom

pointing to parent ecosystem:
https://repo1.maven.org/maven2/io/quarkiverse/primefaces/quarkus-primefaces-ecosystem/3.13.4/quarkus-primefaces-ecosystem-3.13.4.pom

and defining:
<quarkus.version>3.3.0</quarkus.version>
..
<primefaces.version>13.0.1</primefaces.version>
<primefaces-extensions.version>13.0.1</primefaces-extensions.version>
<myfaces.version>4.0.1</myfaces.version>

Coming from https://github.com/quarkiverse/quarkus-primefaces/blob/3.13.4/pom.xml

All clear to me. Thank you.

**Comment by melloware** [comment]
Nice and 13.0.2 is coming out today so look for the new version here after it's published.
