### ISSUE TITLE
Support to Quarkus3 

### ISSUE THREAD

**Issue by nyko29** [quarkiverse/quarkus-primefaces#16]
Hello,

It would be nice to have a migration to quarkus3. As a snapshot for now until Quarkus3 is officaily available. I saw that [quarkus-omnifaces](https://github.com/quarkiverse/quarkus-omnifaces) and [myfaces](https://github.com/apache/myfaces)  now have a branch for quarkus 3. 

The same for this project and the showcase [quarkus-faces](https://github.com/melloware/quarkus-faces) would be awesome :)

**Comment by melloware** [comment]
Yep I am working on that next!

**Comment by nyko29** [comment]
Nice ! Thanks 👍

**Comment by melloware** [comment]
Linked to: https://github.com/melloware/quarkus-faces/issues/151

**Comment by nyko29** [comment]
On my own project, for now I only have quarkus-omnifaces and myfaces with Quarkus3 (I am not using quarkus-primefaces for now).
Jut to let you know that the hot reloading is not working (see https://github.com/quarkusio/quarkus/issues/31513)

I am curious to know if you face the same issue

**Comment by nyko29** [comment]
yeah, I hope stable will be available soon

**Comment by nyko29** [comment]
Well done, I will try it this week. Thanks

**Comment by melloware** [comment]
@all-contributors add @nyko29 for test
