### ISSUE TITLE
Releasing new version of quarkus-primefaces-extensions maven repo

### ISSUE THREAD

**Issue by seklmco** [quarkiverse/quarkus-primefaces#211]
Hello. I am unfamiliar with the process of new releases on maven. A new version of [primefaces-extensions](https://central.sonatype.com/artifact/org.primefaces.extensions/primefaces-extensions/versions), v13.0.12, was recently released. What is the process of releasing a new version of [quarkus-primefaces-extensions](https://central.sonatype.com/artifact/io.quarkiverse.primefaces/quarkus-primefaces-extensions/3.14.1/overview) to reflect the update?

**Comment by melloware** [comment]
i have not really been releasing older version of this quarkus plugin i always just release the new latest branch?

If you are using Quarkus why not update to 14.x?

**Comment by seklmco** [comment]
I believe I've misunderstood your comments from [here](https://github.com/primefaces-extensions/primefaces-extensions/pull/1587). My thinking is that this fix is only available in v13.0.12 and will be available in the next new release, 14.0.2 for example.
I updated quarkus-primefaces-extensions to 3.14.1 (which uses primefaces-extensions 14.0.1) just now, but the code fix is not there.

**Comment by melloware** [comment]
right i have not released 14.0.2 yet.  So your question about 13.12 threw me off.

I update this library whenever i do official PFE releases.  So Quarkus PF 3.14.2 will have this fix in it.

**Comment by seklmco** [comment]
Okay understood. Thank you!

**Comment by melloware** [comment]
3.14.2 is now in Maven Central.

**Comment by seklmco** [comment]
Thank you for the update. Much appreciated
