### ISSUE TITLE
issues with static resources

### ISSUE THREAD

**Issue by nimo23** [quarkiverse/quarkus-primefaces#240]
I use Quarkus Primefaces, all works well so far..

I included general resources in `META-INF/resources` (e.g. a simple test.html (not a .xhtml) or a test.txt).

Now if you go to `localhost:8080/test.txt,` MyFaces will redirect to “Page not found”.  But MyFaces should bypass this non-JSF page.

I don't know if it's a bug or misconfiguration by myself.

**Comment by melloware** [comment]
Works fine for me. I added `\src\main\resources\META-INF\resources\test.html`

Which contains:

```html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html>
```


And ran `mvn quarkus:dev` and hit http://localhost:8000/test.html

![image](https://github.com/user-attachments/assets/b342146a-bf31-4ec1-a3f7-9bcf58888035)
