### ISSUE TITLE
Short review

### ISSUE THREAD

**Issue by tandraschko** [quarkiverse/quarkus-primefaces#7]
in general everything looks good, thanks!
I also like to finally switch from String class names to SomeClass.class.getName

Just some minor stuff:
- ´Primefaces´Processor.java; We should really name it ´PrimeFaces´ like everywhere else in the JSF world
- ANNOTATED_CLASSES - why do we have it? isnt really used?

**Comment by melloware** [comment]
Fixed `Primefaces` to `PrimeFaces` in all files

Removed ANNOTATED CLASSES it was a cut and paste!  Thanks!
