### ISSUE TITLE
MultiModule Build: Resources Do Not Reload

### ISSUE THREAD

**Issue by gesker** [quarkiverse/quarkus-primefaces#75]
Static files under resources, specifically **xhtml**, files are not reloaded when in dev mode when the quarkus project is a maven sub-module within a larger maven project.

Reproducer:

[https://github.com/gesker/sub-module-reload-page-fail-demonstrator](https://github.com/gesker/sub-module-reload-page-fail-demonstrator)

To reproduce:

```
./mvnw clean compile quarkus:dev -pl www
```

1. Browse to localhost:8080
2. Edit[ www/src/main/resources/META-INF/resources/index.xhtml](https://github.com/gesker/sub-module-reload-page-fail-demonstrator/blob/main/www/src/main/resources/META-INF/resources/index.xhtml)
3. Refresh browser

_Note:_ "other" is present just to have a second module in the maven project. It is not used in this example.
_Note:_ There are a couple of environment variables set in **./mvn/maven.config** just to prevent a port conflict between "other" and "www" sub-modules so best to use the wrapper.

Quarkus 3.1.1.Final
Quarkus-Primefaces 3.13.0

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Debian-1) OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing)

This seems to happen in a maven sub-module only. It doesn't appear to be an issue in a standalone project. To double check this assumption I compared the behavior in quarkus:dev to the (quarkus-faces)[https://github.com/melloware/quarkus-faces] project and quarkus:dev works fine in that project; not a sub-module.

I'm pretty sure the issue isn't browser related as this behavior can be replicated on Chrome, Firefox and lynx (command line) browsers. But, if there is something specific I should try on the browser side of things let me know and I will report back. Did manually flush browser cache.

I did comment out any setting with CACHE in the web.xml just in case or at least in an attempt to set the caching behavior back to default.

Just to check if it was maven itself I bumped from 3.8.8 to 3.9.2 and saw no change in behavior. Doesn't really rule out maven but just a data point.

Tried falling back to Quarkus 3.0.4.Final and bad behavior remained.

Did **_NOT_** try falling back to 2.16.17.

I did see that there is a [quarkus.live-reload.watched-resources](https://quarkus.io/guides/all-config#quarkus-core_quarkus.live-reload.watched-resources) setting available, and at first I thought maybe that would be needed for a mulit-module project, but on second thought this didn't seem the correct route to pursue as a full compile and reload shouldn't be necessary for xhtml file changes. 

Also, just try to collect/provide some additional information I added a (plain.html)[https://github.com/gesker/sub-module-reload-page-fail-demonstrator/blob/main/www/src/main/resources/META-INF/resources/plain.html] file in the root of the resources folder. This plain.html file _DOES_ show updated data in dev mode after editing. This file behaving as expected is the reason I circled back to quarkus-faces on this item.

The demonstrator sits at Quarkus 3.1.1.Final and Maven 3.9.2. 

Again, wrapper probably best way to run the demonstrator as I do set some ports so there is no conflict between modules in dev mode in the maven.config file.

**Comment by melloware** [comment]
interesting.  I was pretty sure all loading of resources was handled by Quarkus for any resources found under /META-INF/resources.

**Comment by melloware** [comment]
Also are you running `mvn quarkus:dev` from the root project or from the `www` project?

**Comment by gesker** [comment]
Always from root. 

Right now I'm looking for a an old branch in my current project that was on Quarkus 2.x.

I don't think this was an issue on 2.x but I wouldn't bet the farm on it.

**Comment by melloware** [comment]
When I changed the `html` file I see this..

```
2023-06-13 16:45:24,879 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-6) Files changed but restart not needed - notified extensions in: 0.004s
```

But not when I touch your XHTML file.   So in `RuntimeUpdatesProcessor` it doesn't think this file is changed or needs to be watched but I am not sure why.

Code: https://github.com/quarkusio/quarkus/blob/5c2df5112331ef170c0b0ad83c84c6f853c2d5d6/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L565

**Comment by gesker** [comment]
Before you deep dive... I'm not 100% sure the web.xml is correct. I did comment out all the CACHE configuration items
 - trying to get back to default config - but I had been wondering traffic/filter was in the way or controlling the session in a way that I didn't understand - somehow determined the xhtml files didn't need to be reread -- and I simply hosed the configuration.  
 
It was only after I was sure this wasn't happening in a known good project (quarkus-faces) that I figured I'd better file an issue.

I think my web.xml might be close but I've created complex problems from simple config mistakes before. Hopefully, my stare and compare was good enough to rule the the web.xml out a contributor.

**Comment by melloware** [comment]
Actually I am seeing this message now but still not updating the XHTML page.

2023-06-13 17:26:38,354 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Files changed but restart not needed - notified extensions in: 0.004s

**Comment by tandraschko** [comment]
in general not a primefaces thing, more related to myfaces-core <> quarkus

myfaces should reload all xhtml files in ProjectStage.Dev from classpath
so i think either quarkus does not replace/reload the classloader stuff or MyFaces is not in Development stage or cache configured somehsow

**Comment by tandraschko** [comment]
jakarta.faces.FACELETS_REFRESH_PERIOD — When a page is requested, what interval in seconds should the compiler check for changes. If you don’t want the compiler to check for changes once the page is compiled, then use a value of -1. Setting a low refresh period helps during development to be able to edit pages in a running application.The runtime must also consider the facelets.REFRESH_PERIOD param name as an alias to this param name for backwards compatibility with existing facelets tag libraries.

**Comment by tandraschko** [comment]
thats the problem

this setting should actually be not active in ProjectStage=Dev IMO

@melloware would you like to check if Mojarra ignores this flag in dev stage? 
Otherwise, we should fix it in MyFaces anyway

**Comment by melloware** [comment]
This is what Mojarra does it forces -1 in production mode but in Dev mode if its set in web.xml it uses it but if NOT found it defaults to 2.

```java
 // refresh period
        boolean isProduction = applicationImpl.getProjectStage() == Production;
        String refreshPeriod;
        if (webConfig.isSet(FaceletsDefaultRefreshPeriod)) {
            refreshPeriod = webConfig.getOptionValue(FaceletsDefaultRefreshPeriod);
        } else if (isProduction) {
            refreshPeriod = "-1";
        } else {
            refreshPeriod = FaceletsDefaultRefreshPeriod.getDefaultValue();
        }

```

**Comment by melloware** [comment]
@gesker confirmed removing this setting fixes your issue.

```xml
	<context-param>
		<param-name>jakarta.faces.FACELETS_REFRESH_PERIOD</param-name>
		<param-value>-1</param-value>
	</context-param>
```

You can do this if you want to set it for Production Mode only.

```xml
	<context-param>
		<param-name>jakarta.faces.FACELETS_REFRESH_PERIOD</param-name>
		<param-value>#{facesContext.application.projectStage eq 'Development' ? 2 : -1}</param-value>
	</context-param>
```

**Comment by tandraschko** [comment]
IMO we should fix it in MyFaces

**Comment by melloware** [comment]
ok let me look at MyFaces

**Comment by tandraschko** [comment]
there is just no need to cache in dev mode IMO
but lets create a myfaces issue and a small vote

**Comment by tandraschko** [comment]
also i dont know if EL is supported in this param
at least we have to support it or just ignore it in dev mode

**Comment by melloware** [comment]
https://issues.apache.org/jira/browse/MYFACES-4608
